.TH DEB-TOOLS-NAMEFIX 1 2021-07-19 "deb-tools" "Debian Package Renamer"

.SH NAME
deb-tools-namefix \- Fix the name of a .deb package

.SH SYNOPSIS
.nf
.BR deb-tools-namefix " [\fIpackages\fR]"
.fi

.SH DESCRIPTION
.B deb-tools-namefix
fixes the name of any Debian package to package_version_architecture.deb format.

.SH HOMEPAGE
.I https://github.com/igatjens/deb-tools

.SH AUTHOR
Isaías Gätjens M <igatjens@gmail.com>, and Amaro Martínez
<xoas@airmail.cc>