.TH DEB-TOOLS-PERMCK 1 2021-08-02 "deb-tools" "Debian Package Permissions Checker"

.SH NAME
deb-tools-permck \- Checks the permissions of a .deb package

.SH SYNOPSIS
.nf
.BR deb-tools-permck " [\fIpackages\fR]"
.fi

.SH DESCRIPTION
.B deb-tools-permck
checks the Debian package for permissions issues and generates a report in ~/deb-tools/deb-issue-report.

.SH HOMEPAGE
.I https://github.com/igatjens/deb-tools

.SH AUTHOR
Isaías Gätjens M <igatjens@gmail.com>, and Amaro Martínez
<xoas@airmail.cc>