.TH DEB-TOOLS-PERMFIX 1 2021-08-02 "deb-tools" "Debian Package Permissions Fixer"

.SH NAME
deb-tools-permfix \- Fix the permissions of a .deb package

.SH SYNOPSIS
.nf
.BR deb-tools-permfix " [\fI-i interactive mode\fR] [\fIpackages\fR]"
.fi

.SH DESCRIPTION
.B deb-tools-permfix
fixes the permissions of any Debian package.

.SH HOMEPAGE
.I https://github.com/igatjens/deb-tools

.SH AUTHOR
Isaías Gätjens M <igatjens@gmail.com>, and Amaro Martínez
<xoas@airmail.cc>